artgris_file_manager:
    web_dir: public
    conf:
        default:
            dir: "../public/uploads/"
            tree: true
            upload:
                image_versions: {'thumbnail': {crop: true, max_width: 10, max_height: 10}}
        private:
            dir: "../private"
            type: image
            upload:
                max_width: 10

        tiny:
            dir: "../private"
            type: image
        private_doc:
            dir: "../private"
            regex: '.(pdf|doc)$'
            accept: '.pdf,.doc'
        perso:
            service: "custom_service"